all:
	g++ *.cpp -o hw4 -std=c++11 -lXi -lGLEW -lGLU -lm -lGL -lm -lpthread -ldl -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lglfw3 -lrt -lm -ldl -lXrandr -lXinerama -lXxf86vm -lXext -lXcursor -lXrender -lXfixes -lX11 -lpthread -lxcb -lXau -lXdmcp -ljpeg

mozan:
	g++ *.cpp -o hw4 -std=c++11 -lGL -lglfw -lGLEW -lGLU -lm -ljpeg
